{
 "title": "MyDashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "up service",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(up{})" }
   ]
  },
  {
   "title": "Total HTTP Request by Status Code (1m interval)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "increase(flask_http_request_total[1m])",
     "legendFormat": "{{method}}:{{status}}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "table",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 0 },
   "targets": [
    { "expr": "flask_http_request_total" }
   ]
  },
  {
   "title": "Failed HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{status!~\"2..\"})"
    }
   ]
  },
  {
   "title": "Successful HTTP Requests",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 4, "y": 13 },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_count{status=~\"2..\"}"
    }
   ]
  },
  {
   "title": "Failed HTTP Requests",
   "type": "table",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 13 },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_count{status!~\"2..\"}"
    }
   ]
  },
  {
   "title": "Successful HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{status=~\"2..\"})"
    }
   ]
  }
 ]
}