global:
  scrape_interval:     5s

rule_files:

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'student-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['student-service:15000']
